development:
  adapter: postgresql
  encoding: unicode
  database: egocentric_dev
  pool: 5
  username: ego
  password:

production:
  adapter: mysql
  encoding: unicode
  database: 
  pool: 5
  username: 
  password: 
