development:
  adapter: postgresql
  database: leonards_development
  username: leonards
  password:
  encoding: utf8
  pool: 5

test: &test
  adapter: postgresql
  database: leonards_development
  username: leonards 
  password:
  encoding: utf8
  pool: 5

cucumber:
  <<: *test
